//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIIE_Tutorias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupo()
        {
            this.Cursando = new HashSet<Cursando>();
            this.HorarioGrupo = new HashSet<HorarioGrupo>();
        }
    
        public int idGrupo { get; set; }
        public int idMateria { get; set; }
        public int idMaestro { get; set; }
        public int idSalon { get; set; }
        public string Periodo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cursando> Cursando { get; set; }
        public virtual Materia Materia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioGrupo> HorarioGrupo { get; set; }
        public virtual Maestro Maestro { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
