//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIIE_Tutorias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialAcademico
    {
        public int idHistorialAcademico { get; set; }
        public int idAlumno { get; set; }
        public int idMateria { get; set; }
        public int Estado { get; set; }
        public string Semestre { get; set; }
        public string Año { get; set; }
        public Nullable<int> Calificacion { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
