//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIIE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnosTutoriaRelationship
    {
        public int IdAlumno { get; set; }
        public int IdTutoria { get; set; }
        public Nullable<double> Calificacion { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Tutorias Tutorias { get; set; }
    }
}
