//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIIE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioTutorias
    {
        public int idHorario { get; set; }
        public int TutoriaId { get; set; }
        public string Dia { get; set; }
        public string Entrada { get; set; }
        public string Salida { get; set; }
        public int IdSalon { get; set; }
    
        public virtual Salon Salon { get; set; }
        public virtual Tutorias Tutorias { get; set; }
    }
}
