//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIIE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIIE_dbEntities : DbContext
    {
        public SIIE_dbEntities()
            : base("name=SIIE_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Cursando> Cursando { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<HistorialAcademico> HistorialAcademico { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<HorarioGrupo> HorarioGrupo { get; set; }
        public virtual DbSet<Loginn> Loginn { get; set; }
        public virtual DbSet<Maestro> Maestro { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Salon> Salon { get; set; }
    }
}
